[toolchain]
anchor_version = "0.31.1"

[features]
resolution = false
skip-lint = false

[programs.localnet]
endpoint = "8eGbY1MUKMSRoLTSPxen83hPWfT3zTuCVgj2UbS1kKsL"
oft = "9myHzfqsbJfGbYxpCvVCYqLaB4Co1RCo2a8T4QSkTvcD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./target/deploy/local-runtime-test-wallet.json"

[scripts]
test = "npx jest --config jest.config.ts --runInBand test/anchor"
